CREATE TABLE staff(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,staff_id TEXT NOT NULL REFERENCES staff(id),expires INTEGER NOT NULL,csrf TEXT NOT NULL);
CREATE TABLE articles(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,subtitle TEXT NOT NULL DEFAULT '',body TEXT NOT NULL,category TEXT NOT NULL,region TEXT NOT NULL DEFAULT 'haiti',kind TEXT NOT NULL DEFAULT 'article',image TEXT NOT NULL DEFAULT '',image_credit TEXT NOT NULL DEFAULT '',author TEXT NOT NULL,locale TEXT NOT NULL DEFAULT 'ht',status TEXT NOT NULL DEFAULT 'draft',featured INTEGER NOT NULL DEFAULT 0,demo INTEGER NOT NULL DEFAULT 0,sponsored INTEGER NOT NULL DEFAULT 0,publish_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,sources TEXT NOT NULL DEFAULT '',tags TEXT NOT NULL DEFAULT '',influencer_id TEXT);
CREATE TABLE revisions(id TEXT PRIMARY KEY,article_id TEXT NOT NULL REFERENCES articles(id),data TEXT NOT NULL,staff_id TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE influencers(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,name TEXT NOT NULL,username TEXT NOT NULL,origin TEXT NOT NULL,residence TEXT NOT NULL,category TEXT NOT NULL,bio TEXT NOT NULL,image TEXT NOT NULL DEFAULT '',socials TEXT NOT NULL DEFAULT '{}',languages TEXT NOT NULL DEFAULT 'ht',demo INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'published',created_at TEXT NOT NULL);
CREATE TABLE comments(id TEXT PRIMARY KEY,target_type TEXT NOT NULL,target_id TEXT NOT NULL,parent_id TEXT REFERENCES comments(id),visitor_hash TEXT NOT NULL,name TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE reactions(comment_id TEXT NOT NULL REFERENCES comments(id),visitor_hash TEXT NOT NULL,PRIMARY KEY(comment_id,visitor_hash));
CREATE TABLE reports(id TEXT PRIMARY KEY,target_type TEXT NOT NULL,target_id TEXT NOT NULL,visitor_hash TEXT NOT NULL,reason TEXT NOT NULL,body TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,UNIQUE(target_type,target_id,visitor_hash));
CREATE TABLE submissions(id TEXT PRIMARY KEY,kind TEXT NOT NULL,name TEXT NOT NULL,body TEXT NOT NULL,contact TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL);
CREATE TABLE translations(id TEXT PRIMARY KEY,target_type TEXT NOT NULL,target_id TEXT NOT NULL,version TEXT NOT NULL,locale TEXT NOT NULL,data TEXT NOT NULL,manual INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,UNIQUE(target_type,target_id,version,locale));
CREATE TABLE usage_months(month TEXT PRIMARY KEY,characters INTEGER NOT NULL DEFAULT 0);
CREATE TABLE videos(id TEXT PRIMARY KEY,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',upload_id TEXT UNIQUE,asset_id TEXT UNIQUE,playback_id TEXT,status TEXT NOT NULL DEFAULT 'not_configured',category TEXT NOT NULL DEFAULT 'Entèvyou',locale TEXT NOT NULL DEFAULT 'ht',created_at TEXT NOT NULL);
CREATE TABLE webhook_events(id TEXT PRIMARY KEY,created_at TEXT NOT NULL);
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE audit_logs(id TEXT PRIMARY KEY,staff_id TEXT NOT NULL,action TEXT NOT NULL,target_id TEXT NOT NULL,reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE page_views(id TEXT PRIMARY KEY,article_id TEXT NOT NULL REFERENCES articles(id),visitor_hash TEXT NOT NULL,day TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(article_id,visitor_hash,day));
CREATE TABLE push_subscriptions(visitor_hash TEXT PRIMARY KEY,token TEXT NOT NULL,locale TEXT NOT NULL,topics TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL);
CREATE TABLE campaigns(id TEXT PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,url TEXT NOT NULL,locale TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL);
CREATE TABLE deliveries(campaign_id TEXT NOT NULL REFERENCES campaigns(id),visitor_hash TEXT NOT NULL,status TEXT NOT NULL,PRIMARY KEY(campaign_id,visitor_hash));
CREATE TABLE rate_limits(bucket TEXT PRIMARY KEY,count INTEGER NOT NULL,reset_at INTEGER NOT NULL);
CREATE INDEX article_status_date ON articles(status,publish_at);
CREATE INDEX comment_target ON comments(target_type,target_id,status);
CREATE INDEX submission_status ON submissions(status);
CREATE INDEX report_status ON reports(status);
CREATE INDEX translation_target ON translations(target_id,locale);
CREATE INDEX views_date ON page_views(created_at);
