CREATE TABLE categories(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,slug TEXT UNIQUE NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE tags(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,slug TEXT UNIQUE NOT NULL);
CREATE TABLE seo_metadata(target_type TEXT NOT NULL,target_id TEXT NOT NULL,locale TEXT NOT NULL,title TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',noindex INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(target_type,target_id,locale));
CREATE TABLE influencer_metrics(id TEXT PRIMARY KEY,influencer_id TEXT NOT NULL REFERENCES influencers(id),platform TEXT NOT NULL,followers INTEGER NOT NULL,source_url TEXT NOT NULL,observed_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE visitor_bans(visitor_hash TEXT PRIMARY KEY,expires_at TEXT NOT NULL,reason TEXT NOT NULL,staff_id TEXT NOT NULL REFERENCES staff(id));
CREATE TABLE translation_jobs(id TEXT PRIMARY KEY,target_type TEXT NOT NULL,target_id TEXT NOT NULL,version TEXT NOT NULL,locale TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',attempts INTEGER NOT NULL DEFAULT 0,next_try TEXT NOT NULL,lease_at TEXT,error TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,UNIQUE(target_type,target_id,version,locale));
CREATE TABLE supported_languages(code TEXT PRIMARY KEY,name TEXT NOT NULL,rtl INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL);
CREATE TABLE newsletter_subscribers(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,locale TEXT NOT NULL,token_hash TEXT UNIQUE NOT NULL,status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL);
CREATE TABLE ad_placements(id TEXT PRIMARY KEY,name TEXT NOT NULL,image_url TEXT NOT NULL,target_url TEXT NOT NULL,locale TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
ALTER TABLE campaigns ADD COLUMN topic TEXT NOT NULL DEFAULT '';
ALTER TABLE campaigns ADD COLUMN scheduled_at TEXT;
ALTER TABLE campaigns ADD COLUMN influencer_id TEXT;
ALTER TABLE deliveries ADD COLUMN created_at TEXT NOT NULL DEFAULT '';
ALTER TABLE deliveries ADD COLUMN updated_at TEXT NOT NULL DEFAULT '';
ALTER TABLE deliveries ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE deliveries ADD COLUMN error TEXT NOT NULL DEFAULT '';
ALTER TABLE comments ADD COLUMN subscribe_reply INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media_assets ADD COLUMN size_bytes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media_assets ADD COLUMN width INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media_assets ADD COLUMN height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media_assets ADD COLUMN error TEXT NOT NULL DEFAULT '';
CREATE INDEX translation_queue_status ON translation_jobs(status,next_try);
CREATE INDEX delivery_queue_status ON deliveries(status,updated_at);
CREATE INDEX campaign_schedule ON campaigns(status,scheduled_at);
